# Travis CI (MIT License) configuration file
# @link https://travis-ci.org/
# @link https://github.com/jrfnl/make-phpcs-work-for-you/tree/master/travis-examples

# Only run on the following branches
branches:
  only:
    - master

# Declare project language
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
  fast_finish: true

  include:
    - php: '7.1'
    - php: '7.2'
      env: SNIFF=1
    - php: '7.3'

before_install:
  - composer self-update;
  - composer install;

script:
  # Search for PHP syntax errors
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # Run PHPCS
  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs; fi
  # Run PHP Unit
  - vendor/bin/phpunit

notifications:
  on_success: never
  on_failure: always